#!/bin/bash

[ -z "$DFM_STATUS_START_OF_COLOR" ] && DFM_STATUS_START_OF_COLOR="\033[30;"
[ -z "$DFM_STATUS_GREEN" ] && DFM_STATUS_GREEN="$DFM_STATUS_START_OF_COLOR""42m"
[ -z "$DFM_STATUS_YELLOW" ] && DFM_STATUS_YELLOW="$DFM_STATUS_START_OF_COLOR""43m"
[ -z "$DFM_STATUS_RED" ] && DFM_STATUS_RED="$DFM_STATUS_START_OF_COLOR""41m"
[ -z "$DFM_STATUS_END_OF_COLOR" ] && DFM_STATUS_END_OF_COLOR="\033[0m"
[ -z "$DFM_STATUS_PRINT" ] && DFM_STATUS_PRINT="default"
[ -z "$DFM_STATUS_PRINT_MESSAGE" ] && DFM_STATUS_PRINT_MESSAGE=""