#!/bin/bash

[ -z "$DFM_SHOW_ALL_VERSIONS" ] && DFM_SHOW_ALL_VERSIONS=false
[ -z "$DFM_SHOW_DOCKER_VERSION" ] && DFM_SHOW_DOCKER_VERSION=false
[ -z "$DFM_SHOW_FZF_VERSION" ] && DFM_SHOW_FZF_VERSION=false
[ -z "$DFM_SHOW_GRADLE_VERSION" ] && DFM_SHOW_GRADLE_VERSION=false
[ -z "$DFM_SHOW_HELM_VERSION" ] && DFM_SHOW_HELM_VERSION=false
[ -z "$DFM_SHOW_HUGO_VERSION" ] && DFM_SHOW_HUGO_VERSION=false
[ -z "$DFM_SHOW_ISTIO_VERSION" ] && DFM_SHOW_ISTIO_VERSION=false
[ -z "$DFM_SHOW_JAVA_VERSION" ] && DFM_SHOW_JAVA_VERSION=false
[ -z "$DFM_SHOW_KIND_VERSION" ] && DFM_SHOW_KIND_VERSION=false
[ -z "$DFM_SHOW_KUBECTL_VERSION" ] && DFM_SHOW_KUBECTL_VERSION=false
[ -z "$DFM_SHOW_MINIKUBE_VERSION" ] && DFM_SHOW_MINIKUBE_VERSION=false
[ -z "$DFM_SHOW_NODE_VERSION" ] && DFM_SHOW_NODE_VERSION=false
[ -z "$DFM_SHOW_SKAFFOLD_VERSION" ] && DFM_SHOW_SKAFFOLD_VERSION=false
[ -z "$DFM_SHOW_TERRAFORM_VERSION" ] && DFM_SHOW_TERRAFORM_VERSION=false
[ -z "$DFM_SHOW_YARN_VERSION" ] && DFM_SHOW_YARN_VERSION=false
[ -z "$DFM_SHOW_YEOMAN_VERSION" ] && DFM_SHOW_YEOMAN_VERSION=false