FROM asciinema/asciicast2gif

WORKDIR /usr/share/fonts/truetype

# for zsh powerline + nerd fonts
COPY fonts/MesloLGSNFBoldItalic.ttf .
COPY fonts/MesloLGSNFBold.ttf .
COPY fonts/MesloLGSNFItalic.ttf .
COPY fonts/MesloLGSNFRegular.ttf .

WORKDIR /data