#!/bin/bash

[ -z "$DFM_DOCKER_BUILD" ] && DFM_DOCKER_BUILD=false
[ -z "$DFM_DOCKER_LOGIN" ] && DFM_DOCKER_LOGIN=false
[ -z "$DFM_DOCKER_NO_CACHE" ] && DFM_DOCKER_NO_CACHE=false
[ -z "$DFM_DOCKER_REMOVE" ] && DFM_DOCKER_REMOVE=false
[ -z "$DFM_DOCKER_RUN" ] && DFM_DOCKER_RUN=false
[ -z "$DFM_DOCKER_START" ] && DFM_DOCKER_START=false
[ -z "$DFM_DOCKER_EXEC" ] && DFM_DOCKER_EXEC=false
[ -z "$DFM_TRANSIENT_CONTAINER" ] && DFM_TRANSIENT_CONTAINER=false
[ -z "$DFM_DOCKER_CONTAINER_NAME" ] && DFM_DOCKER_CONTAINER_NAME="dev-env"
[ -z "$DFM_DOCKER_BUILD_STAGE" ] && DFM_DOCKER_BUILD_STAGE="base"
[ -z "$DFM_DOCKER_USER" ] && DFM_DOCKER_USER="1000:1000"
[ -z "$DFM_DOCKERFILE" ] && DFM_DOCKERFILE="Dockerfile"
[ -z "$DFM_DOCKER_IMAGE_NAME" ] && DFM_DOCKER_IMAGE_NAME="dev-env"
[ -z "$DFM_DOCKER_MOUNT_PATH" ] && DFM_DOCKER_MOUNT_PATH="$PWD"
[ -z "$DFM_DOCKER_REGISTRY" ] && DFM_DOCKER_REGISTRY=""