#!/bin/bash

# ----------------------- INSTALL & UNINSTALL VARIABLES ---------------------- #

[ -z "$DFM_INSTALL_PATH" ] && DFM_INSTALL_PATH="/opt"
[ -z "$DFM_SHARE_PATH" ] && DFM_SHARE_PATH="/usr/local/bin"
[ -z "$DFM_OPERATING_SYSTEM" ] && DFM_OPERATING_SYSTEM="darwin"
[ -z "$DFM_OPERATING_SYSTEM_OVERRIDE" ] && DFM_OPERATING_SYSTEM_OVERRIDE=false
[ -z "$DFM_SUDO" ] && DFM_SUDO=""
[ -z "$DFM_FZF_VERSION" ] && DFM_FZF_VERSION="0.27.2"
[ -z "$DFM_GOLANG_VERSION" ] && DFM_GOLANG_VERSION="1.17"
[ -z "$DFM_GRADLE_VERSION" ] && DFM_GRADLE_VERSION="6.9"
[ -z "$DFM_HELM_VERSION" ] && DFM_HELM_VERSION="3.6.3"
[ -z "$DFM_HUGO_VERSION" ] && DFM_HUGO_VERSION="0.87.0"
[ -z "$DFM_ISTIO_VERSION" ] && DFM_ISTIO_VERSION="1.10.3"
[ -z "$DFM_KIND_VERSION" ] && DFM_KIND_VERSION="0.11.1"
[ -z "$DFM_KUBECTL_VERSION" ] && DFM_KUBECTL_VERSION="1.22.0"
[ -z "$DFM_MINIKUBE_VERSION" ] && DFM_MINIKUBE_VERSION="1.22.0"
[ -z "$DFM_NEOVIM_VERSION" ] && DFM_NEOVIM_VERSION="0.5.0"
[ -z "$DFM_NODE_VERSION" ] && DFM_NODE_VERSION="14.17.0"
[ -z "$DFM_P10K_VERSION" ] && DFM_P10K_VERSION="1.15.0"
[ -z "$DFM_SKAFFOLD_VERSION" ] && DFM_SKAFFOLD_VERSION="1.29.0"
[ -z "$DFM_TERRAFORM_VERSION" ] && DFM_TERRAFORM_VERSION="1.0.4"
[ -z "$DFM_YARN_VERSION" ] && DFM_YARN_VERSION="1.22.10"

# ----------------------------- INSTALL VARIABLES ---------------------------- #

[ -z "$DFM_INSTALL_ALL" ] && DFM_INSTALL_ALL=false
[ -z "$DFM_INSTALL_DRY_RUN" ] && DFM_INSTALL_DRY_RUN=false
[ -z "$DFM_INSTALL_OVERWRITE" ] && DFM_INSTALL_OVERWRITE=false
[ -z "$DFM_INSTALL_VERSION_CHECK" ] && DFM_INSTALL_VERSION_CHECK=false
[ -z "$DFM_INSTALL_DOCKER" ] && DFM_INSTALL_DOCKER=false
[ -z "$DFM_INSTALL_FZF" ] && DFM_INSTALL_FZF=false
[ -z "$DFM_INSTALL_GOLANG" ] && DFM_INSTALL_GOLANG=false
[ -z "$DFM_INSTALL_GRADLE" ] && DFM_INSTALL_GRADLE=false
[ -z "$DFM_INSTALL_HELM" ] && DFM_INSTALL_HELM=false
[ -z "$DFM_INSTALL_HUGO" ] && DFM_INSTALL_HUGO=false
[ -z "$DFM_INSTALL_ISTIO" ] && DFM_INSTALL_ISTIO=false
[ -z "$DFM_INSTALL_JAVA" ] && DFM_INSTALL_JAVA=false
[ -z "$DFM_INSTALL_KIND" ] && DFM_INSTALL_KIND=false
[ -z "$DFM_INSTALL_KUBECTL" ] && DFM_INSTALL_KUBECTL=false
[ -z "$DFM_INSTALL_MINIKUBE" ] && DFM_INSTALL_MINIKUBE=false
[ -z "$DFM_INSTALL_NEOVIM" ] && DFM_INSTALL_NEOVIM=false
[ -z "$DFM_INSTALL_NODE" ] && DFM_INSTALL_NODE=false
[ -z "$DFM_INSTALL_ZSH" ] && DFM_INSTALL_ZSH=false
[ -z "$DFM_INSTALL_P10K" ] && DFM_INSTALL_P10K=false
[ -z "$DFM_INSTALL_SKAFFOLD" ] && DFM_INSTALL_SKAFFOLD=false
[ -z "$DFM_INSTALL_TERRAFORM" ] && DFM_INSTALL_TERRAFORM=false
[ -z "$DFM_INSTALL_YARN" ] && DFM_INSTALL_YARN=false
[ -z "$DFM_CURL_FLAGS" ] && DFM_CURL_FLAGS=""
[ -z "$DFM_WGET_FLAGS" ] && DFM_WGET_FLAGS=""

# ---------------------------- UNINSTALL VARIABLES --------------------------- #

[ -z "$DFM_UNINSTALL_ALL" ] && DFM_UNINSTALL_ALL=false
[ -z "$DFM_UNINSTALL_VERSION_CHECK" ] && DFM_UNINSTALL_VERSION_CHECK=false
[ -z "$DFM_UNINSTALL_DOCKER" ] && DFM_UNINSTALL_DOCKER=false
[ -z "$DFM_UNINSTALL_DRY_RUN" ] && DFM_UNINSTALL_DRY_RUN=false
[ -z "$DFM_UNINSTALL_GRADLE" ] && DFM_UNINSTALL_GRADLE=false
[ -z "$DFM_UNINSTALL_HELM" ] && DFM_UNINSTALL_HELM=false
[ -z "$DFM_UNINSTALL_HUGO" ] && DFM_UNINSTALL_HUGO=false
[ -z "$DFM_UNINSTALL_ISTIO" ] && DFM_UNINSTALL_ISTIO=false
[ -z "$DFM_UNINSTALL_JAVA" ] && DFM_UNINSTALL_JAVA=false
[ -z "$DFM_UNINSTALL_KIND" ] && DFM_UNINSTALL_KIND=false
[ -z "$DFM_UNINSTALL_KUBECTL" ] && DFM_UNINSTALL_KUBECTL=false
[ -z "$DFM_UNINSTALL_MINIKUBE" ] && DFM_UNINSTALL_MINIKUBE=false
[ -z "$DFM_UNINSTALL_NODE" ] && DFM_UNINSTALL_NODE=false
[ -z "$DFM_UNINSTALL_SKAFFOLD" ] && DFM_UNINSTALL_SKAFFOLD=false
[ -z "$DFM_UNINSTALL_MINIKUBE" ] && DFM_UNINSTALL_MINIKUBE=false
[ -z "$DFM_UNINSTALL_TERRAFORM" ] && DFM_UNINSTALL_TERRAFORM=false
[ -z "$DFM_UNINSTALL_YARN" ] && DFM_UNINSTALL_YARN=false