# docker aliases
alias doc='docker'
alias dk='docker kill'
alias dkall='docker kill $(docker ps -aq)'
alias drm='docker rm'
alias drmf='docker rm -f'
alias drmi='docker rmi -f'
alias drmall='docker rm $(docker ps -aq)'
alias drmid='docker rmi $(docker images -f "dangling=true" -q)'
alias di='docker images'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dn='docker network'
alias dnls='docker network ls'
alias dsp='docker system prune'
alias dspa='docker system prune -a'
alias dstart='docker start -ai'
