# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

[[ -f $ZSH/oh-my-zsh.sh ]] && . $ZSH/oh-my-zsh.sh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/aliases.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/aliases.zsh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/exports.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/exports.zsh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/functions.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/functions.zsh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/plugins.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/plugins.zsh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/misc.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/misc.zsh
# If using starship, comment this out
[[ -f $HOME/.p10k.zsh ]] && . $HOME/.p10k.zsh
[[ -f $HOME/.fzf.zsh ]] && . $HOME/.fzf.zsh
