[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/exports.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/exports.zsh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/aliases.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/aliases.zsh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/functions.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/functions.zsh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/plugins.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/plugins.zsh
[[ -f $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/misc.zsh ]] && . $XDG_CONFIG_HOME/dotfiles/dotfiles/zsh/misc.zsh
[[ -f $ZSH/oh-my-zsh.sh ]] && . $ZSH/oh-my-zsh.sh
# If using starship, comment this out
[[ -f $HOME/.p10k.zsh ]] && . $HOME/.p10k.zsh
