# Common git shortcuts
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git pull'
alias gpu='git push'
alias gf='git fetch'
alias gb='git branch'
alias gco='git checkout'
alias gd='git diff'
alias gl='git log --oneline -20'
alias glog='git log --graph --oneline --decorate'
